### PR TITLE
less margin on top for non-scrollable login page

### PR DESCRIPTION
**Pull request by gavinkalika**
To resolve issue #107 

I added my own styles to app.less
Then ran 

> lessc  resources/assets/less/app.less public/css/app.css

Then update the gulp.js file to include 

> public/css/app.css

Please give me your concerns about this approach. I'm pretty new to css compilers and gulp/grunt

---
This change is [Reviewable](https://reviewable.io/reviews/timegridio/timegrid/166)

### CODE REVIEW

**Comment by gavinkalika** [comment]
@alariva :)

**Comment by alariva** [comment]
@gavinkalika Now I see the changes to the app.less, which seem to be fine (I still have to test and compile them). But you are still including many files that should not be altered within this commit.

**Comment by gavinkalika** [comment]
@alariva I made my file changes more precise on this commit - only two files changed.

But you need to run gulp to see my changes on the UI. Hope that is okay

**Comment by alariva** [comment]
@gavinkalika The code is ok, but the only change that should take place here is *adding* this block to the `app.less`.

```
.login-box,
.register-box {
  width: 360px;
  margin: 1% auto;
}
```

Of course, I'd need to run gulp to recompile assets, but that's no worry. Would you redo this PR so I can merge it with your authorship ?

Sorry for late reply.

Thanks!!

**Comment by gavinkalika** [comment]
Cool. I updated the PR

**Comment by alariva** [comment]
Thanks!!

**Pull request merged**
