### PR TITLE
Add language picker on landing page

### PR DESCRIPTION
**Pull request by gavinkalika**
@alariva 
For issue #140

Any tips or advice is welcomed!

---
This change is [Reviewable](https://reviewable.io/reviews/timegridio/timegrid/167)

### CODE REVIEW

**Comment by gavinkalika** [comment]
awesome!

**Comment by alariva** [comment]
The enhancement works neat. We will only need to polish the commits that alter more lines than required (indentation styling mostly).

**Comment by gavinkalika** [comment]
I see. I will rebase interactively and tidy those indentation issues

**Comment by gavinkalika** [comment]
fix indentation issues

**Pull request merged**
