### PR TITLE
Add sweet alert when deleting a service [WIP]

### PR DESCRIPTION
**Pull request by softnayr**
This change is [Reviewable](https://reviewable.io/reviews/timegridio/timegrid/181)

### CODE REVIEW

**Comment by softnayr** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/timegridio/timegrid/181)*

**Comment by alariva** [comment]
*[.env.example, line 0 at r1](https://reviewable.io:443/reviews/timegridio/timegrid/181#-KqLUnovJGlwMlsPAEvb:-KqLUnowF5DdyCw5zVxF:b22o7za) ([raw file](https://github.com/timegridio/timegrid/blob/5ab01f9b8bf1b8ab38d1ac60a90fe0b6bd5fb2c2/.env.example#L0)):*
Please do not commit this file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/timegridio/timegrid/181)*

**Comment by alariva** [comment]
*[composer.lock, line 0 at r1](https://reviewable.io:443/reviews/timegridio/timegrid/181#-KqLVG7qhMKWCv35o4Eh:-KqLVG7ros0RjUgsSKnD:bqicl23) ([raw file](https://github.com/timegridio/timegrid/blob/5ab01f9b8bf1b8ab38d1ac60a90fe0b6bd5fb2c2/composer.lock#L0)):*
Only the added package should be added. Did you run `composer update` instead of `composer require` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/timegridio/timegrid/181)*

**Comment by alariva** [comment]
*[package-lock.json, line 1 at r1](https://reviewable.io:443/reviews/timegridio/timegrid/181#-KqLVkMtItykHRIov8ak:-KqLVkMtItykHRIov8al:b22o7za) ([raw file](https://github.com/timegridio/timegrid/blob/5ab01f9b8bf1b8ab38d1ac60a90fe0b6bd5fb2c2/package-lock.json#L1)):*
> ```JSON
> {
> ```

Please do not commit this file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/timegridio/timegrid/181)*

**Comment by alariva** [comment]
*[app/Http/Controllers/Manager/BusinessServiceController.php, line 188 at r1](https://reviewable.io:443/reviews/timegridio/timegrid/181#-KqLVte-MVJjnm-a3M4w:-KqLVte-MVJjnm-a3M4x:b-viehno) ([raw file](https://github.com/timegridio/timegrid/blob/5ab01f9b8bf1b8ab38d1ac60a90fe0b6bd5fb2c2/app/Http/Controllers/Manager/BusinessServiceController.php#L188)):*
> ```PHP
>         $this->authorize('manageServices', $business);
> ```

Please do not commit whitespaces and/or change indentation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/timegridio/timegrid/181)*

**Comment by alariva** [comment]
*[app/Http/Controllers/Manager/BusinessServiceController.php, line 199 at r1](https://reviewable.io:443/reviews/timegridio/timegrid/181#-KqLVzp1Mczjtp0oxC-b:-KqLVzp1Mczjtp0oxC-c:beci98w) ([raw file](https://github.com/timegridio/timegrid/blob/5ab01f9b8bf1b8ab38d1ac60a90fe0b6bd5fb2c2/app/Http/Controllers/Manager/BusinessServiceController.php#L199)):*
> ```PHP
>         $service->forceDelete();
> 
>         //flash()->success(trans('manager.services.msg.destroy.success'));
> ```

You may remove commented out lines

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/timegridio/timegrid/181)*

**Comment by alariva** [comment]
*[app/Http/Controllers/Manager/BusinessServiceController.php, line 201 at r1](https://reviewable.io:443/reviews/timegridio/timegrid/181#-KqLW2D1pfi_cKMZxlkF:-KqLW2D1pfi_cKMZxlkG:bsrfkwe) ([raw file](https://github.com/timegridio/timegrid/blob/5ab01f9b8bf1b8ab38d1ac60a90fe0b6bd5fb2c2/app/Http/Controllers/Manager/BusinessServiceController.php#L201)):*
> ```PHP
>         //flash()->success(trans('manager.services.msg.destroy.success'));
> 
>         alert()->success(trans('manager.services.msg.destroy.success'))->autoclose(3500);
> ```

Looks good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/timegridio/timegrid/181)*

**Comment by alariva** [comment]
*[config/app.php, line 187 at r1](https://reviewable.io:443/reviews/timegridio/timegrid/181#-KqLWB0ApxbcZPeVJVQj:-KqLWB0ApxbcZPeVJVQk:b-47fafm) ([raw file](https://github.com/timegridio/timegrid/blob/5ab01f9b8bf1b8ab38d1ac60a90fe0b6bd5fb2c2/config/app.php#L187)):*
> ```PHP
>         Timegridio\ICalReader\ICalReaderServiceProvider::class,
>         Seanstewart\PlanConfig\PlanConfigServiceProvider::class,
>         UxWeb\SweetAlert\SweetAlertServiceProvider::class,
> ```

looks good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/timegridio/timegrid/181)*

**Comment by alariva** [comment]
*[config/app.php, line 282 at r1](https://reviewable.io:443/reviews/timegridio/timegrid/181#-KqLWCnBgCXJEpvegzBs:-KqLWCnBgCXJEpvegzBt:b-47fafm) ([raw file](https://github.com/timegridio/timegrid/blob/5ab01f9b8bf1b8ab38d1ac60a90fe0b6bd5fb2c2/config/app.php#L282)):*
> ```PHP
>         'Widget'     => Caffeinated\Widgets\Facades\Widget::class,
>         'Plan'       => Seanstewart\PlanConfig\Plan::class,
>         'SweetAlert'      => UxWeb\SweetAlert\SweetAlert::class,
> ```

looks good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/timegridio/timegrid/181)*

**Comment by alariva** [comment]
*[resources/views/layouts/app.blade.php, line 16 at r1](https://reviewable.io:443/reviews/timegridio/timegrid/181#-KqLWQcEpBgMj2jC42RV:-KqLWQcEpBgMj2jC42RW:b32wtd) ([raw file](https://github.com/timegridio/timegrid/blob/5ab01f9b8bf1b8ab38d1ac60a90fe0b6bd5fb2c2/resources/views/layouts/app.blade.php#L16)):*
> ```PHP
>     
>     <link rel="stylesheet" href="{{ asset('css/app.min.css') }}">
>     <link rel="stylesheet" href="{{ asset('css/sweetalert.css') }}">
> ```

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/timegridio/timegrid/181)*

**Comment by alariva** [comment]
*[resources/views/layouts/app.blade.php, line 187 at r1](https://reviewable.io:443/reviews/timegridio/timegrid/181#-KqLWSR5gt7A8bXqi-w4:-KqLWSR5gt7A8bXqi-w5:b32wtd) ([raw file](https://github.com/timegridio/timegrid/blob/5ab01f9b8bf1b8ab38d1ac60a90fe0b6bd5fb2c2/resources/views/layouts/app.blade.php#L187)):*
> ```PHP
> 
> <script src="{{ asset('js/app.min.js') }}"></script>
> <script src="{{ asset('js/sweetalert.min.js') }}"></script>
> ```

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/timegridio/timegrid/181)*

**Comment by alariva** [comment]
*[resources/views/manager/businesses/show.blade.php, line 28 at r1](https://reviewable.io:443/reviews/timegridio/timegrid/181#-KqLWV5eV6VUGMlxc6t-:-KqLWV5eV6VUGMlxc6t0:b-96ubtr) ([raw file](https://github.com/timegridio/timegrid/blob/5ab01f9b8bf1b8ab38d1ac60a90fe0b6bd5fb2c2/resources/views/manager/businesses/show.blade.php#L28)):*
> ```PHP
>     <div class="row">
>         <div class="col-md-12">
>             {{-- {!! Alert::warning(Button::withIcon(Icon::time())
> ```

do not comment, just remove lines

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/timegridio/timegrid/181)*

**Comment by alariva** [comment]
*[resources/views/manager/businesses/services/index.blade.php, line 110 at r1](https://reviewable.io:443/reviews/timegridio/timegrid/181#-KqLW_hFSTdZWfSPObVH:-KqLW_hFSTdZWfSPObVI:b2fngst) ([raw file](https://github.com/timegridio/timegrid/blob/5ab01f9b8bf1b8ab38d1ac60a90fe0b6bd5fb2c2/resources/views/manager/businesses/services/index.blade.php#L110)):*
> ```PHP
>                //  }
> 
>                swal({
> ```

looks ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/timegridio/timegrid/181)*

**Comment by alariva** [comment]
Reviewed 1 of 11 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/timegridio/timegrid/181)*

**Comment by alariva** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/timegridio/timegrid/181)*

**Pull request closed without merging**
